const championsData = [
  {
    id: "266",
    name: "Aatrox",
    icon: "/lol-guesser/champions/Aatrox.png",
    gender: "Male",
    positions: ["Top"],
    species: "Darkin",
    resource: "Manaless",
    rangeType: "Melee",
    regions: ["Runeterra", "Shurima"],
    releaseYear: 2013
  },
  {
    id: "103",
    name: "Ahri",
    icon: "/lol-guesser/champions/Ahri.png",
    gender: "Female",
    positions: ["Mid"],
    species: "Vastayan",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Ionia"],
    releaseYear: 2011
  },
  {
    id: "84",
    name: "Akali",
    icon: "/lol-guesser/champions/Akali.png",
    gender: "Female",
    positions: ["Mid", "Top"],
    species: "Human",
    resource: "Energy",
    rangeType: "Melee",
    regions: ["Ionia"],
    releaseYear: 2010
  },
  {
    id: "166",
    name: "Akshan",
    icon: "/lol-guesser/champions/Akshan.png",
    gender: "Male",
    positions: ["Mid", "Top"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Shurima"],
    releaseYear: 2021
  },
  {
    id: "12",
    name: "Alistar",
    icon: "/lol-guesser/champions/Alistar.png",
    gender: "Male",
    positions: ["Support"],
    species: "Minotaur",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Runeterra"],
    releaseYear: 2009
  },
  {
    id: "32",
    name: "Amumu",
    icon: "/lol-guesser/champions/Amumu.png",
    gender: "Male",
    positions: ["Jungle"],
    species: "Yordle",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Shurima"],
    releaseYear: 2009
  },
  {
    id: "1",
    name: "Annie",
    icon: "/lol-guesser/champions/Annie.png",
    gender: "Female",
    positions: ["Mid"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Noxus"],
    releaseYear: 2009
  },
  {
    id: "34",
    name: "Anivia",
    icon: "/lol-guesser/champions/Anivia.png",
    gender: "Female",
    positions: ["Mid"],
    species: "God-Warrior",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Freljord"],
    releaseYear: 2009
  },
  {
    id: "523",
    name: "Aphelios",
    icon: "/lol-guesser/champions/Aphelios.png",
    gender: "Male",
    positions: ["ADC"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Targon"],
    releaseYear: 2019
  },
  {
    id: "22",
    name: "Ashe",
    icon: "/lol-guesser/champions/Ashe.png",
    gender: "Female",
    positions: ["ADC"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Freljord"],
    releaseYear: 2009
  },
  {
    id: "136",
    name: "Aurelion Sol",
    icon: "/lol-guesser/champions/AurelionSol.png",
    gender: "Male",
    positions: ["Mid"],
    species: "Celestial",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Runeterra", "Targon"],
    releaseYear: 2016
  },
  {
    id: "268",
    name: "Azir",
    icon: "/lol-guesser/champions/Azir.png",
    gender: "Male",
    positions: ["Mid"],
    species: "God-Warrior",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Shurima"],
    releaseYear: 2014
  },
  {
    id: "432",
    name: "Bard",
    icon: "/lol-guesser/champions/Bard.png",
    gender: "Male",
    positions: ["Support"],
    species: "Celestial",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Runeterra"],
    releaseYear: 2015
  },
  {
    id: "200",
    name: "Bel'Veth",
    icon: "/lol-guesser/champions/BelVeth.png",
    gender: "Female",
    positions: ["Jungle"],
    species: "Void",
    resource: "Manaless",
    rangeType: "Melee",
    regions: ["Void"],
    releaseYear: 2022
  },
  {
    id: "53",
    name: "Blitzcrank",
    icon: "/lol-guesser/champions/Blitzcrank.png",
    gender: "Other",
    positions: ["Support"],
    species: "Golem",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Zaun"],
    releaseYear: 2009
  },
  {
    id: "63",
    name: "Brand",
    icon: "/lol-guesser/champions/Brand.png",
    gender: "Male",
    positions: ["Support", "Mid"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Runeterra", "Freljord"],
    releaseYear: 2011
  },
  {
    id: "201",
    name: "Braum",
    icon: "/lol-guesser/champions/Braum.png",
    gender: "Male",
    positions: ["Support"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Freljord"],
    releaseYear: 2014
  },
  {
    id: "51",
    name: "Caitlyn",
    icon: "/lol-guesser/champions/Caitlyn.png",
    gender: "Female",
    positions: ["ADC"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Piltover"],
    releaseYear: 2011
  },
  {
    id: "164",
    name: "Camille",
    icon: "/lol-guesser/champions/Camille.png",
    gender: "Female",
    positions: ["Top"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Piltover"],
    releaseYear: 2016
  },
  {
    id: "69",
    name: "Cassiopeia",
    icon: "/lol-guesser/champions/Cassiopeia.png",
    gender: "Female",
    positions: ["Mid"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Noxus", "Shurima"],
    releaseYear: 2010
  },
  {
    id: "31",
    name: "Cho'Gath",
    icon: "/lol-guesser/champions/ChoGath.png",
    gender: "Male",
    positions: ["Top"],
    species: "Void",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Void"],
    releaseYear: 2009
  },
  {
    id: "42",
    name: "Corki",
    icon: "/lol-guesser/champions/Corki.png",
    gender: "Male",
    positions: ["Mid"],
    species: "Yordle",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Bandle City"],
    releaseYear: 2009
  },
  {
    id: "122",
    name: "Darius",
    icon: "/lol-guesser/champions/Darius.png",
    gender: "Male",
    positions: ["Top"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Noxus"],
    releaseYear: 2012
  },
  {
    id: "131",
    name: "Diana",
    icon: "/lol-guesser/champions/Diana.png",
    gender: "Female",
    positions: ["Jungle", "Mid"],
    species: "Aspect",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Targon"],
    releaseYear: 2012
  },
  {
    id: "119",
    name: "Draven",
    icon: "/lol-guesser/champions/Draven.png",
    gender: "Male",
    positions: ["ADC"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Noxus"],
    releaseYear: 2012
  },
  {
    id: "36",
    name: "Dr. Mundo",
    icon: "/lol-guesser/champions/DrMundo.png",
    gender: "Male",
    positions: ["Top", "Jungle"],
    species: "Chemically Altered",
    resource: "Health Costs",
    rangeType: "Melee",
    regions: ["Zaun"],
    releaseYear: 2009
  },
  {
    id: "245",
    name: "Ekko",
    icon: "/lol-guesser/champions/Ekko.png",
    gender: "Male",
    positions: ["Mid", "Jungle"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Zaun"],
    releaseYear: 2015
  },
  {
    id: "60",
    name: "Elise",
    icon: "/lol-guesser/champions/Elise.png",
    gender: "Female",
    positions: ["Jungle"],
    species: "Human",
    resource: "Mana",
    rangeType: ["Melee", "Ranged"],
    regions: ["Shadow Isles", "Noxus"],
    releaseYear: 2012
  },
  {
    id: "28",
    name: "Evelynn",
    icon: "/lol-guesser/champions/Evelynn.png",
    gender: "Female",
    positions: ["Jungle"],
    species: "Demon",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Runeterra"],
    releaseYear: 2009
  },
  {
    id: "81",
    name: "Ezreal",
    icon: "/lol-guesser/champions/Ezreal.png",
    gender: "Male",
    positions: ["ADC"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Piltover"],
    releaseYear: 2010
  },
  {
    id: "9",
    name: "Fiddlesticks",
    icon: "/lol-guesser/champions/Fiddlesticks.png",
    gender: "Other",
    positions: ["Jungle"],
    species: "Demon",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Runeterra"],
    releaseYear: 2009
  },
  {
    id: "114",
    name: "Fiora",
    icon: "/lol-guesser/champions/Fiora.png",
    gender: "Female",
    positions: ["Top"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Demacia"],
    releaseYear: 2012
  },
  {
    id: "105",
    name: "Fizz",
    icon: "/lol-guesser/champions/Fizz.png",
    gender: "Male",
    positions: ["Mid"],
    species: "Yordle",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Bilgewater"],
    releaseYear: 2011
  },
  {
    id: "3",
    name: "Galio",
    icon: "/lol-guesser/champions/Galio.png",
    gender: "Male",
    positions: ["Mid", "Support"],
    species: "Golem",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Demacia"],
    releaseYear: 2010
  },
  {
    id: "41",
    name: "Gangplank",
    icon: "/lol-guesser/champions/Gangplank.png",
    gender: "Male",
    positions: ["Top"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Bilgewater"],
    releaseYear: 2009
  },
  {
    id: "86",
    name: "Garen",
    icon: "/lol-guesser/champions/Garen.png",
    gender: "Male",
    positions: ["Top"],
    species: "Human",
    resource: "Manaless",
    rangeType: "Melee",
    regions: ["Demacia"],
    releaseYear: 2010
  },
  {
    id: "150",
    name: "Gnar",
    icon: "/lol-guesser/champions/Gnar.png",
    gender: "Male",
    positions: ["Top"],
    species: "Yordle",
    resource: "Rage",
    rangeType: "Ranged",
    regions: ["Freljord"],
    releaseYear: 2014
  },
  {
    id: "79",
    name: "Gragas",
    icon: "/lol-guesser/champions/Gragas.png",
    gender: "Male",
    positions: ["Jungle", "Top"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Freljord"],
    releaseYear: 2010
  },
  {
    id: "104",
    name: "Graves",
    icon: "/lol-guesser/champions/Graves.png",
    gender: "Male",
    positions: ["Jungle"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Bilgewater"],
    releaseYear: 2011
  },
  {
    id: "887",
    name: "Gwen",
    icon: "/lol-guesser/champions/Gwen.png",
    gender: "Female",
    positions: ["Top"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Shadow Isles", "Camavor"],
    releaseYear: 2021
  },
  {
    id: "120",
    name: "Hecarim",
    icon: "/lol-guesser/champions/Hecarim.png",
    gender: "Male",
    positions: ["Jungle"],
    species: "Undead",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Shadow Isles"],
    releaseYear: 2012
  },
  {
    id: "74",
    name: "Heimerdinger",
    icon: "/lol-guesser/champions/Heimerdinger.png",
    gender: "Male",
    positions: ["Mid", "Support"],
    species: "Yordle",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Piltover"],
    releaseYear: 2009
  },
  {
    id: "420",
    name: "Illaoi",
    icon: "/lol-guesser/champions/Illaoi.png",
    gender: "Female",
    positions: ["Top"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Bilgewater"],
    releaseYear: 2015
  },
  {
    id: "39",
    name: "Irelia",
    icon: "/lol-guesser/champions/Irelia.png",
    gender: "Female",
    positions: ["Top", "Mid"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Ionia"],
    releaseYear: 2010
  },
  {
    id: "427",
    name: "Ivern",
    icon: "/lol-guesser/champions/Ivern.png",
    gender: "Male",
    positions: ["Jungle"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Ionia", "Freljord"],
    releaseYear: 2016
  },
  {
    id: "40",
    name: "Janna",
    icon: "/lol-guesser/champions/Janna.png",
    gender: "Female",
    positions: ["Support"],
    species: "God-Warrior",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Zaun"],
    releaseYear: 2009
  },
  {
    id: "59",
    name: "Jarvan IV",
    icon: "/lol-guesser/champions/JarvanIV.png",
    gender: "Male",
    positions: ["Jungle"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Demacia"],
    releaseYear: 2011
  },
  {
    id: "24",
    name: "Jax",
    icon: "/lol-guesser/champions/Jax.png",
    gender: "Male",
    positions: ["Top", "Jungle"],
    species: "Unknown",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Runeterra", "Icathia"],
    releaseYear: 2009
  },
  {
    id: "126",
    name: "Jayce",
    icon: "/lol-guesser/champions/Jayce.png",
    gender: "Male",
    positions: ["Top", "Mid"],
    species: "Human",
    resource: "Mana",
    rangeType: ["Melee", "Ranged"],
    regions: ["Piltover"],
    releaseYear: 2012
  },
  {
    id: "202",
    name: "Jhin",
    icon: "/lol-guesser/champions/Jhin.png",
    gender: "Male",
    positions: ["ADC"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Ionia"],
    releaseYear: 2016
  },
  {
    id: "222",
    name: "Jinx",
    icon: "/lol-guesser/champions/Jinx.png",
    gender: "Female",
    positions: ["ADC"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Zaun"],
    releaseYear: 2013
  },
  {
    id: "145",
    name: "Kai'Sa",
    icon: "/lol-guesser/champions/KaiSa.png",
    gender: "Female",
    positions: ["ADC"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Void", "Shurima"],
    releaseYear: 2018
  },
  {
    id: "429",
    name: "Kalista",
    icon: "/lol-guesser/champions/Kalista.png",
    gender: "Female",
    positions: ["ADC"],
    species: "Undead",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Shadow Isles"],
    releaseYear: 2014
  },
  {
    id: "43",
    name: "Karma",
    icon: "/lol-guesser/champions/Karma.png",
    gender: "Female",
    positions: ["Support"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Ionia"],
    releaseYear: 2011
  },
  {
    id: "30",
    name: "Karthus",
    icon: "/lol-guesser/champions/Karthus.png",
    gender: "Male",
    positions: ["Jungle"],
    species: "Undead",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Shadow Isles"],
    releaseYear: 2009
  },
  {
    id: "38",
    name: "Kassadin",
    icon: "/lol-guesser/champions/Kassadin.png",
    gender: "Male",
    positions: ["Mid"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Void", "Shurima"],
    releaseYear: 2009
  },
  {
    id: "55",
    name: "Katarina",
    icon: "/lol-guesser/champions/Katarina.png",
    gender: "Female",
    positions: ["Mid"],
    species: "Human",
    resource: "Manaless",
    rangeType: "Melee",
    regions: ["Noxus"],
    releaseYear: 2009
  },
  {
    id: "10",
    name: "Kayle",
    icon: "/lol-guesser/champions/Kayle.png",
    gender: "Female",
    positions: ["Top"],
    species: "Aspect",
    resource: "Mana",
    rangeType: ["Melee", "Ranged"],
    regions: ["Demacia", "Targon"],
    releaseYear: 2009
  },
  {
    id: "141",
    name: "Kayn",
    icon: "/lol-guesser/champions/Kayn.png",
    gender: "Male",
    positions: ["Jungle"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Ionia", "Noxus"],
    releaseYear: 2017
  },
  {
    id: "85",
    name: "Kennen",
    icon: "/lol-guesser/champions/Kennen.png",
    gender: "Male",
    positions: ["Top"],
    species: "Yordle",
    resource: "Energy",
    rangeType: "Ranged",
    regions: ["Ionia"],
    releaseYear: 2010
  },
  {
    id: "121",
    name: "Kha'Zix",
    icon: "/lol-guesser/champions/KhaZix.png",
    gender: "Male",
    positions: ["Jungle"],
    species: "Void",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Void"],
    releaseYear: 2012
  },
  {
    id: "203",
    name: "Kindred",
    icon: "/lol-guesser/champions/Kindred.png",
    gender: "Other",
    positions: ["Jungle"],
    species: "God",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Runeterra"],
    releaseYear: 2015
  },
  {
    id: "240",
    name: "Kled",
    icon: "/lol-guesser/champions/Kled.png",
    gender: "Male",
    positions: ["Top"],
    species: "Yordle",
    resource: "Courage",
    rangeType: "Melee",
    regions: ["Noxus"],
    releaseYear: 2016
  },
  {
    id: "96",
    name: "Kog'Maw",
    icon: "/lol-guesser/champions/KogMaw.png",
    gender: "Male",
    positions: ["ADC"],
    species: "Void",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Void"],
    releaseYear: 2010
  },
  {
    id: "897",
    name: "K'Sante",
    icon: "/lol-guesser/champions/KSante.png",
    gender: "Male",
    positions: ["Top"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Shurima"],
    releaseYear: 2022
  },
  {
    id: "7",
    name: "LeBlanc",
    icon: "/lol-guesser/champions/LeBlanc.png",
    gender: "Female",
    positions: ["Mid"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Noxus"],
    releaseYear: 2010
  },
  {
    id: "64",
    name: "Lee Sin",
    icon: "/lol-guesser/champions/Lee Sin.png",
    gender: "Male",
    positions: ["Jungle"],
    species: "Human",
    resource: "Energy",
    rangeType: "Melee",
    regions: ["Ionia"],
    releaseYear: 2011
  },
  {
    id: "89",
    name: "Leona",
    icon: "/lol-guesser/champions/Leona.png",
    gender: "Female",
    positions: ["Support"],
    species: "Aspect",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Targon"],
    releaseYear: 2011
  },
  {
    id: "876",
    name: "Lillia",
    icon: "/lol-guesser/champions/Lillia.png",
    gender: "Female",
    positions: ["Jungle"],
    species: "Spirit",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Ionia"],
    releaseYear: 2020
  },
  {
    id: "127",
    name: "Lissandra",
    icon: "/lol-guesser/champions/Lissandra.png",
    gender: "Female",
    positions: ["Mid"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Freljord"],
    releaseYear: 2013
  },
  {
    id: "236",
    name: "Lucian",
    icon: "/lol-guesser/champions/Lucian.png",
    gender: "Male",
    positions: ["ADC"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Demacia", "Shadow Isles"],
    releaseYear: 2013
  },
  {
    id: "117",
    name: "Lulu",
    icon: "/lol-guesser/champions/Lulu.png",
    gender: "Female",
    positions: ["Support"],
    species: "Yordle",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Bandle City"],
    releaseYear: 2012
  },
  {
    id: "99",
    name: "Lux",
    icon: "/lol-guesser/champions/Lux.png",
    gender: "Female",
    positions: ["Mid", "Support"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Demacia"],
    releaseYear: 2010
  },
  {
    id: "54",
    name: "Malphite",
    icon: "/lol-guesser/champions/Malphite.png",
    gender: "Male",
    positions: ["Top"],
    species: "Golem",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Ixtal", "Shurima"],
    releaseYear: 2009
  },
  {
    id: "90",
    name: "Malzahar",
    icon: "/lol-guesser/champions/Malzahar.png",
    gender: "Male",
    positions: ["Mid"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Void", "Shurima"],
    releaseYear: 2010
  },
  {
    id: "57",
    name: "Maokai",
    icon: "/lol-guesser/champions/Maokai.png",
    gender: "Male",
    positions: ["Support", "Jungle"],
    species: "Spirit",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Shadow Isles"],
    releaseYear: 2011
  },
  {
    id: "11",
    name: "Master Yi",
    icon: "/lol-guesser/champions/MasterYi.png",
    gender: "Male",
    positions: ["Jungle"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Ionia"],
    releaseYear: 2009
  },
  {
    id: "902",
    name: "Milio",
    icon: "/lol-guesser/champions/Milio.png",
    gender: "Male",
    positions: ["Support"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Ixtal"],
    releaseYear: 2023
  },
  {
    id: "21",
    name: "Miss Fortune",
    icon: "/lol-guesser/champions/MissFortune.png",
    gender: "Female",
    positions: ["ADC"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Bilgewater"],
    releaseYear: 2010
  },
  {
    id: "62",
    name: "Wukong",
    icon: "/lol-guesser/champions/Wukong.png",
    gender: "Male",
    positions: ["Top", "Jungle"],
    species: "Vastayan",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Ionia"],
    releaseYear: 2011
  },
  {
    id: "82",
    name: "Mordekaiser",
    icon: "/lol-guesser/champions/Mordekaiser.png",
    gender: "Male",
    positions: ["Top"],
    species: "Revenant",
    resource: "Shield",
    rangeType: "Melee",
    regions: ["Noxus"],
    releaseYear: 2010
  },
  {
    id: "25",
    name: "Morgana",
    icon: "/lol-guesser/champions/Morgana.png",
    gender: "Female",
    positions: ["Support"],
    species: "Aspect",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Demacia", "Targon"],
    releaseYear: 2009
  },
  {
    id: "267",
    name: "Nami",
    icon: "/lol-guesser/champions/Nami.png",
    gender: "Female",
    positions: ["Support"],
    species: "Vastayan",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Runeterra"],
    releaseYear: 2012
  },
  {
    id: "75",
    name: "Nasus",
    icon: "/lol-guesser/champions/Nasus.png",
    gender: "Male",
    positions: ["Top"],
    species: "God-Warrior",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Shurima"],
    releaseYear: 2009
  },
  {
    id: "111",
    name: "Nautilus",
    icon: "/lol-guesser/champions/Nautilus.png",
    gender: "Male",
    positions: ["Support"],
    species: "Revenant",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Bilgewater"],
    releaseYear: 2012
  },
  {
    id: "518",
    name: "Neeko",
    icon: "/lol-guesser/champions/Neeko.png",
    gender: "Female",
    positions: ["Mid", "Support"],
    species: "Vastayan",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Ixtal"],
    releaseYear: 2018
  },
  {
    id: "76",
    name: "Nidalee",
    icon: "/lol-guesser/champions/Nidalee.png",
    gender: "Female",
    positions: ["Jungle"],
    species: "Human",
    resource: "Mana",
    rangeType: ["Melee", "Ranged"],
    regions: ["Ixtal"],
    releaseYear: 2009
  },
  {
    id: "895",
    name: "Nilah",
    icon: "/lol-guesser/champions/Nilah.png",
    gender: "Female",
    positions: ["ADC"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Kathkan"],
    releaseYear: 2022
  },
  {
    id: "56",
    name: "Nocturne",
    icon: "/lol-guesser/champions/Nocturne.png",
    gender: "Male",
    positions: ["Jungle"],
    species: "Demon",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Runeterra"],
    releaseYear: 2011
  },
  {
    id: "20",
    name: "Nunu & Willump",
    icon: "/lol-guesser/champions/Nunu.png",
    gender: "Male",
    positions: ["Jungle"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Freljord"],
    releaseYear: 2009
  },
  {
    id: "2",
    name: "Olaf",
    icon: "/lol-guesser/champions/Olaf.png",
    gender: "Male",
    positions: ["Top", "Jungle"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Freljord"],
    releaseYear: 2010
  },
  {
    id: "61",
    name: "Orianna",
    icon: "/lol-guesser/champions/Orianna.png",
    gender: "Female",
    positions: ["Mid"],
    species: "Golem",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Piltover"],
    releaseYear: 2011
  },
  {
    id: "516",
    name: "Ornn",
    icon: "/lol-guesser/champions/Ornn.png",
    gender: "Male",
    positions: ["Top"],
    species: "God",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Freljord"],
    releaseYear: 2017
  },
  {
    id: "80",
    name: "Pantheon",
    icon: "/lol-guesser/champions/Pantheon.png",
    gender: "Male",
    positions: ["Top", "Mid", "Support"],
    species: "Aspect",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Targon"],
    releaseYear: 2010
  },
  {
    id: "78",
    name: "Poppy",
    icon: "/lol-guesser/champions/Poppy.png",
    gender: "Female",
    positions: ["Top", "Jungle"],
    species: "Yordle",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Demacia", "Bandle City"],
    releaseYear: 2010
  },
  {
    id: "555",
    name: "Pyke",
    icon: "/lol-guesser/champions/Pyke.png",
    gender: "Male",
    positions: ["Support"],
    species: "Revenant",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Bilgewater"],
    releaseYear: 2018
  },
  {
    id: "246",
    name: "Qiyana",
    icon: "/lol-guesser/champions/Qiyana.png",
    gender: "Female",
    positions: ["Mid"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Ixtal"],
    releaseYear: 2019
  },
  {
    id: "133",
    name: "Quinn",
    icon: "/lol-guesser/champions/Quinn.png",
    gender: "Female",
    positions: ["Top"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Demacia"],
    releaseYear: 2013
  },
  {
    id: "497",
    name: "Rakan",
    icon: "/lol-guesser/champions/Rakan.png",
    gender: "Male",
    positions: ["Support"],
    species: "Vastayan",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Ionia"],
    releaseYear: 2017
  },
  {
    id: "33",
    name: "Rammus",
    icon: "/lol-guesser/champions/Rammus.png",
    gender: "Male",
    positions: ["Jungle"],
    species: "God-Warrior",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Shurima"],
    releaseYear: 2009
  },
  {
    id: "421",
    name: "Rek'Sai",
    icon: "/lol-guesser/champions/RekSai.png",
    gender: "Female",
    positions: ["Jungle"],
    species: "Void",
    resource: "Rage",
    rangeType: "Melee",
    regions: ["Void", "Shurima"],
    releaseYear: 2014
  },
  {
    id: "526",
    name: "Rell",
    icon: "/lol-guesser/champions/Rell.png",
    gender: "Female",
    positions: ["Support"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Noxus"],
    releaseYear: 2020
  },
  {
    id: "888",
    name: "Renata Glasc",
    icon: "/lol-guesser/champions/Renata.png",
    gender: "Female",
    positions: ["Support"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Zaun"],
    releaseYear: 2022
  },
  {
    id: "58",
    name: "Renekton",
    icon: "/lol-guesser/champions/Renekton.png",
    gender: "Male",
    positions: ["Top"],
    species: "God-Warrior",
    resource: "Fury",
    rangeType: "Melee",
    regions: ["Shurima"],
    releaseYear: 2011
  },
  {
    id: "107",
    name: "Rengar",
    icon: "/lol-guesser/champions/Rengar.png",
    gender: "Male",
    positions: ["Jungle", "Top"],
    species: "Vastayan",
    resource: "Ferocity",
    rangeType: "Melee",
    regions: ["Ixtal"],
    releaseYear: 2012
  },
  {
    id: "92",
    name: "Riven",
    icon: "/lol-guesser/champions/Riven.png",
    gender: "Female",
    positions: ["Top"],
    species: "Human",
    resource: "Manaless",
    rangeType: "Melee",
    regions: ["Ionia", "Noxus"],
    releaseYear: 2011
  },
  {
    id: "68",
    name: "Rumble",
    icon: "/lol-guesser/champions/Rumble.png",
    gender: "Male",
    positions: ["Top", "Mid"],
    species: "Yordle",
    resource: "Heat",
    rangeType: "Melee",
    regions: ["Bandle City"],
    releaseYear: 2011
  },
  {
    id: "13",
    name: "Ryze",
    icon: "/lol-guesser/champions/Ryze.png",
    gender: "Male",
    positions: ["Mid", "Top"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Runeterra"],
    releaseYear: 2009
  },
  {
    id: "360",
    name: "Samira",
    icon: "/lol-guesser/champions/Samira.png",
    gender: "Female",
    positions: ["ADC"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Noxus", "Shurima"],
    releaseYear: 2020
  },
  {
    id: "113",
    name: "Sejuani",
    icon: "/lol-guesser/champions/Sejuani.png",
    gender: "Female",
    positions: ["Jungle"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Freljord"],
    releaseYear: 2012
  },
  {
    id: "235",
    name: "Senna",
    icon: "/lol-guesser/champions/Senna.png",
    gender: "Female",
    positions: ["Support", "ADC"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Shadow Isles"],
    releaseYear: 2019
  },
  {
    id: "147",
    name: "Seraphine",
    icon: "/lol-guesser/champions/Seraphine.png",
    gender: "Female",
    positions: ["Support", "Mid"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Piltover", "Zaun"],
    releaseYear: 2020
  },
  {
    id: "875",
    name: "Sett",
    icon: "/lol-guesser/champions/Sett.png",
    gender: "Male",
    positions: ["Top"],
    species: "Vastayan",
    resource: "Grit",
    rangeType: "Melee",
    regions: ["Ionia"],
    releaseYear: 2020
  },
  {
    id: "35",
    name: "Shaco",
    icon: "/lol-guesser/champions/Shaco.png",
    gender: "Male",
    positions: ["Jungle"],
    species: "Spirit",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Runeterra"],
    releaseYear: 2009
  },
  {
    id: "98",
    name: "Shen",
    icon: "/lol-guesser/champions/Shen.png",
    gender: "Male",
    positions: ["Top"],
    species: "Human",
    resource: "Energy",
    rangeType: "Melee",
    regions: ["Ionia"],
    releaseYear: 2010
  },
  {
    id: "102",
    name: "Shyvana",
    icon: "/lol-guesser/champions/Shyvana.png",
    gender: "Female",
    positions: ["Jungle"],
    species: "Dragon",
    resource: "Fury",
    rangeType: "Melee",
    regions: ["Demacia"],
    releaseYear: 2011
  },
  {
    id: "27",
    name: "Singed",
    icon: "/lol-guesser/champions/Singed.png",
    gender: "Male",
    positions: ["Top"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Zaun"],
    releaseYear: 2009
  },
  {
    id: "14",
    name: "Sion",
    icon: "/lol-guesser/champions/Sion.png",
    gender: "Male",
    positions: ["Top"],
    species: "Revenant",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Noxus"],
    releaseYear: 2009
  },
  {
    id: "15",
    name: "Sivir",
    icon: "/lol-guesser/champions/Sivir.png",
    gender: "Female",
    positions: ["ADC"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Shurima"],
    releaseYear: 2009
  },
  {
    id: "72",
    name: "Skarner",
    icon: "/lol-guesser/champions/Skarner.png",
    gender: "Male",
    positions: ["Jungle"],
    species: "Brackern",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Shurima"],
    releaseYear: 2011
  },
  {
    id: "37",
    name: "Sona",
    icon: "/lol-guesser/champions/Sona.png",
    gender: "Female",
    positions: ["Support"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Demacia", "Ionia"],
    releaseYear: 2010
  },
  {
    id: "16",
    name: "Soraka",
    icon: "/lol-guesser/champions/Soraka.png",
    gender: "Female",
    positions: ["Support"],
    species: "Celestial",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Targon"],
    releaseYear: 2009
  },
  {
    id: "50",
    name: "Swain",
    icon: "/lol-guesser/champions/Swain.png",
    gender: "Male",
    positions: ["Mid", "Support"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Noxus"],
    releaseYear: 2010
  },
  {
    id: "517",
    name: "Sylas",
    icon: "/lol-guesser/champions/Sylas.png",
    gender: "Male",
    positions: ["Mid"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Demacia", "Freljord"],
    releaseYear: 2019
  },
  {
    id: "134",
    name: "Syndra",
    icon: "/lol-guesser/champions/Syndra.png",
    gender: "Female",
    positions: ["Mid"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Ionia"],
    releaseYear: 2012
  },
  {
    id: "223",
    name: "Tahm Kench",
    icon: "/lol-guesser/champions/TahmKench.png",
    gender: "Male",
    positions: ["Support", "Top"],
    species: "Demon",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Bilgewater", "Runeterra"],
    releaseYear: 2015
  },
  {
    id: "163",
    name: "Taliyah",
    icon: "/lol-guesser/champions/Taliyah.png",
    gender: "Female",
    positions: ["Mid", "Jungle"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Shurima"],
    releaseYear: 2016
  },
  {
    id: "91",
    name: "Talon",
    icon: "/lol-guesser/champions/Talon.png",
    gender: "Male",
    positions: ["Mid"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Noxus"],
    releaseYear: 2011
  },
  {
    id: "44",
    name: "Taric",
    icon: "/lol-guesser/champions/Taric.png",
    gender: "Male",
    positions: ["Support"],
    species: "Aspect",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Targon", "Demacia"],
    releaseYear: 2009
  },
  {
    id: "17",
    name: "Teemo",
    icon: "/lol-guesser/champions/Teemo.png",
    gender: "Male",
    positions: ["Top"],
    species: "Yordle",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Bandle City"],
    releaseYear: 2009
  },
  {
    id: "412",
    name: "Thresh",
    icon: "/lol-guesser/champions/Thresh.png",
    gender: "Male",
    positions: ["Support"],
    species: "Undead",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Shadow Isles"],
    releaseYear: 2013
  },
  {
    id: "18",
    name: "Tristana",
    icon: "/lol-guesser/champions/Tristana.png",
    gender: "Female",
    positions: ["ADC"],
    species: "Yordle",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Bandle City"],
    releaseYear: 2009
  },
  {
    id: "48",
    name: "Trundle",
    icon: "/lol-guesser/champions/Trundle.png",
    gender: "Male",
    positions: ["Jungle", "Top"],
    species: "Troll",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Freljord"],
    releaseYear: 2010
  },
  {
    id: "23",
    name: "Tryndamere",
    icon: "/lol-guesser/champions/Tryndamere.png",
    gender: "Male",
    positions: ["Top"],
    species: "Human",
    resource: "Fury",
    rangeType: "Melee",
    regions: ["Freljord"],
    releaseYear: 2009
  },
  {
    id: "4",
    name: "Twisted Fate",
    icon: "/lol-guesser/champions/TwistedFate.png",
    gender: "Male",
    positions: ["Mid"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Bilgewater"],
    releaseYear: 2009
  },
  {
    id: "29",
    name: "Twitch",
    icon: "/lol-guesser/champions/Twitch.png",
    gender: "Male",
    positions: ["ADC"],
    species: "Chemically Altered",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Zaun"],
    releaseYear: 2009
  },
  {
    id: "77",
    name: "Udyr",
    icon: "/lol-guesser/champions/Udyr.png",
    gender: "Male",
    positions: ["Jungle"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Freljord", "Ionia"],
    releaseYear: 2009
  },
  {
    id: "6",
    name: "Urgot",
    icon: "/lol-guesser/champions/Urgot.png",
    gender: "Male",
    positions: ["Top"],
    species: "Chemically Altered",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Zaun"],
    releaseYear: 2010
  },
  {
    id: "110",
    name: "Varus",
    icon: "/lol-guesser/champions/Varus.png",
    gender: "Male",
    positions: ["ADC", "Mid"],
    species: "Darkin",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Ionia", "Runeterra"],
    releaseYear: 2012
  },
  {
    id: "67",
    name: "Vayne",
    icon: "/lol-guesser/champions/Vayne.png",
    gender: "Female",
    positions: ["ADC", "Top"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Demacia"],
    releaseYear: 2011
  },
  {
    id: "45",
    name: "Veigar",
    icon: "/lol-guesser/champions/Veigar.png",
    gender: "Male",
    positions: ["Mid"],
    species: "Yordle",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Bandle City", "Runeterra"],
    releaseYear: 2009
  },
  {
    id: "161",
    name: "Vel'Koz",
    icon: "/lol-guesser/champions/VelKoz.png",
    gender: "Male",
    positions: ["Mid", "Support"],
    species: "Void",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Void"],
    releaseYear: 2014
  },
  {
    id: "711",
    name: "Vex",
    icon: "/lol-guesser/champions/Vex.png",
    gender: "Female",
    positions: ["Mid"],
    species: "Yordle",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Bandle City", "Shadow Isles"],
    releaseYear: 2021
  },
  {
    id: "254",
    name: "Vi",
    icon: "/lol-guesser/champions/Vi.png",
    gender: "Female",
    positions: ["Jungle"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Piltover", "Zaun"],
    releaseYear: 2012
  },
  {
    id: "234",
    name: "Viego",
    icon: "/lol-guesser/champions/Viego.png",
    gender: "Male",
    positions: ["Jungle"],
    species: "Undead",
    resource: "Manaless",
    rangeType: "Melee",
    regions: ["Shadow Isles", "Camavor"],
    releaseYear: 2021
  },
  {
    id: "112",
    name: "Viktor",
    icon: "/lol-guesser/champions/Viktor.png",
    gender: "Male",
    positions: ["Mid"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Zaun"],
    releaseYear: 2011
  },
  {
    id: "8",
    name: "Vladimir",
    icon: "/lol-guesser/champions/Vladimir.png",
    gender: "Male",
    positions: ["Mid", "Top"],
    species: "Human",
    resource: "Bloodthirst",
    rangeType: "Ranged",
    regions: ["Noxus", "Shadow Isles"],
    releaseYear: 2010
  },
  {
    id: "106",
    name: "Volibear",
    icon: "/lol-guesser/champions/Volibear.png",
    gender: "Male",
    positions: ["Top", "Jungle"],
    species: "God",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Freljord"],
    releaseYear: 2011
  },
  {
    id: "19",
    name: "Warwick",
    icon: "/lol-guesser/champions/Warwick.png",
    gender: "Male",
    positions: ["Jungle"],
    species: "Chemically Altered",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Zaun"],
    releaseYear: 2009
  },
  {
    id: "498",
    name: "Xayah",
    icon: "/lol-guesser/champions/Xayah.png",
    gender: "Female",
    positions: ["ADC"],
    species: "Vastayan",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Ionia"],
    releaseYear: 2017
  },
  {
    id: "101",
    name: "Xerath",
    icon: "/lol-guesser/champions/Xerath.png",
    gender: "Male",
    positions: ["Mid", "Support"],
    species: "God-Warrior",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Shurima"],
    releaseYear: 2011
  },
  {
    id: "5",
    name: "Xin Zhao",
    icon: "/lol-guesser/champions/XinZhao.png",
    gender: "Male",
    positions: ["Jungle"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Demacia", "Ionia"],
    releaseYear: 2010
  },
  {
    id: "157",
    name: "Yasuo",
    icon: "/lol-guesser/champions/Yasuo.png",
    gender: "Male",
    positions: ["Mid", "Top"],
    species: "Human",
    resource: "Flow",
    rangeType: "Melee",
    regions: ["Ionia"],
    releaseYear: 2013
  },
  {
    id: "777",
    name: "Yone",
    icon: "/lol-guesser/champions/Yone.png",
    gender: "Male",
    positions: ["Mid", "Top"],
    species: "Human",
    resource: "Flow",
    rangeType: "Melee",
    regions: ["Ionia"],
    releaseYear: 2020
  },
  {
    id: "83",
    name: "Yorick",
    icon: "/lol-guesser/champions/Yorick.png",
    gender: "Male",
    positions: ["Top"],
    species: "Human",
    resource: "Mana",
    rangeType: "Melee",
    regions: ["Shadow Isles"],
    releaseYear: 2011
  },
  {
    id: "350",
    name: "Yuumi",
    icon: "/lol-guesser/champions/Yuumi.png",
    gender: "Female",
    positions: ["Support"],
    species: "Magical Cat",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Bandle City"],
    releaseYear: 2019
  },
  {
    id: "154",
    name: "Zac",
    icon: "/lol-guesser/champions/Zac.png",
    gender: "Male",
    positions: ["Jungle"],
    species: "Golem",
    resource: "Health Costs",
    rangeType: "Melee",
    regions: ["Zaun"],
    releaseYear: 2013
  },
  {
    id: "238",
    name: "Zed",
    icon: "/lol-guesser/champions/Zed.png",
    gender: "Male",
    positions: ["Mid"],
    species: "Human",
    resource: "Energy",
    rangeType: "Melee",
    regions: ["Ionia"],
    releaseYear: 2012
  },
  {
    id: "221",
    name: "Zeri",
    icon: "/lol-guesser/champions/Zeri.png",
    gender: "Female",
    positions: ["ADC"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Zaun"],
    releaseYear: 2022
  },
  {
    id: "115",
    name: "Ziggs",
    icon: "/lol-guesser/champions/Ziggs.png",
    gender: "Male",
    positions: ["Mid"],
    species: "Yordle",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Zaun"],
    releaseYear: 2012
  },
  {
    id: "26",
    name: "Zilean",
    icon: "/lol-guesser/champions/Zilean.png",
    gender: "Male",
    positions: ["Support"],
    species: "Human",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Runeterra", "Icathia"],
    releaseYear: 2009
  },
  {
    id: "142",
    name: "Zoe",
    icon: "/lol-guesser/champions/Zoe.png",
    gender: "Female",
    positions: ["Mid"],
    species: "Aspect",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Targon"],
    releaseYear: 2017
  },
  {
    id: "143",
    name: "Zyra",
    icon: "/lol-guesser/champions/Zyra.png",
    gender: "Female",
    positions: ["Support"],
    species: "Plant",
    resource: "Mana",
    rangeType: "Ranged",
    regions: ["Ixtal"],
    releaseYear: 2012
  }
];

export default championsData;

export interface Champion {
  id: string;
  name: string;
  icon: string;
  gender: "Male" | "Female" | "Other";
  positions: string[];
  species: string;
  resource: string;
  rangeType: "Melee" | "Ranged";
  regions: string[];
  releaseYear: number;
}